src/Entity/Alert.php
<?php

namespace App\Entity;

use App\Repository\AlertRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AlertRepository::class)]
class Alert
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $keyword = null;

    #[ORM\ManyToOne(inversedBy: 'alerts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column]
    private ?int $minimum_notation = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKeyword(): ?string
    {
        return $this->keyword;
    }

    public function setKeyword(string $keyword): self
    {
        $this->keyword = $keyword;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getMinimumNotation(): ?int
    {
        return $this->minimum_notation;
    }

    public function setMinimumNotation(int $minimum_notation): self
    {
        $this->minimum_notation = $minimum_notation;

        return $this;
    }
}

templates/components/comment.html.twig
<div class="card">
    <div class="card-header d-flex flex-column">
        <span class="fw-bold">
        {{ commentaire.user.pseudo }}
        </span>
        <span class="text-muted">
            Posté le {{ commentaire.publishedAt | date('d/m/Y') }} à {{ commentaire.publishedAt | date('H:i') }}
        </span>
    </div>
    <div class="card-body">
        {{ commentaire.comment }}
    </div>
</div>

templates/components/notation.html.twig
<div class="border-1 d-flex border-secondary border notation rounded-pill px-2 py-1 gap-3 mb-2">
  <form method="post" action="{{ path('app_publication_like', {id: publication.id, type: 'dislike'}) }}">
    <button type="submit" class="btn btn-link p-0">
      <i class="bi bi-dash-lg text-primary"></i>
    </button>
  </form>
  <div class="{{ publication.notation > 0 ? 'text-danger' : 'text-primary'}}">{{ publication.notation }}°</div>
  <form method="post" action="{{ path('app_publication_like', {id: publication.id, type: 'like'}) }}">
    <button type="submit" class="btn btn-link p-0">
      <i class="bi bi-plus-lg text-danger"></i>
    </button>
  </form>
</div>

templates/components/profilAlert.html.twig
<div class="d-flex flex-column gap-3 p-3">
    <span class="fw-bold h4">Alertes - Mes mots clés</span>
    <a href="{{ path('app_alert_new') }}" class="btn btn-primary">Ajouter un mot clé</a>
    <div class="d-flex gap-3 flex-column ">
        {% for alerte in alerts %}
            <div class="d-flex justify-content-between align-items-center w-100 border-bottom pb-2">
                <span class="h5">
                    {{ alerte.keyword }}
                </span>
                <div class="d-flex gap-3 align-items-center justify-content-between">
                    <span>
                        Notation minimum :
                        {{ alerte.minimumNotation }}
                    </span>
                    <form method="post" action="{{ path('app_alert_delete', {'id': alerte.id}) }}">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ alerte.id) }}">
                        <button type="submit" class="btn btn-danger">Supprimer</button>
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/components/profilAlertPublication.html.twig
<div class="d-flex flex-column gap-5">
    {% for publication in publications %}
        {{ component('publication', {
            publication: publication
        }) }}
    {% else %}
        <p class="text-center">Aucune publication</p>
    {% endfor %}
</div>

templates/components/profilDeals.html.twig
<div class="d-flex flex-column gap-3 align-items-start">
    <div class="d-flex flex-column gap-5 w-100">
        {% for deal in deals %}
            {{ component('publication', {
                publication: deal,
            }) }}
            <form method="post" action="
                {% if deal.deal %}
                    {{path("app_deal_delete", {'id': deal.deal.id})}}
                {% else %}
                    {{path("app_code_promo_delete",{'id': deal.codePromo.id})}}
                {% endif %}"
                  onsubmit="return confirm('Voulez vous vraiment supprimer cette publication ?')">
                {% if deal.deal %}
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ deal.deal.id ) }}">
                {% else %}
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ deal.codePromo.id ) }}">
                {% endif %}
                <button type="submit" class="btn btn-danger">Supprimer</button>
            </form>
        {% else %}
            <p class="text-center">Aucune publication publié</p>
        {% endfor %}
    </div>
</div>

templates/components/profilSetting.html.twig
<div class="card-body card-profil-body">
    {{ form_start(form) }}
    <div class="form-outline mb-4 form-floating text-light">
        {{ form_row(form.pseudo, {label: 'Pseudo'}) }}
    </div>
    <div class="form-outline mb-4 form-floating text-light">
        {{ form_row(form.email, {label: 'Email'}) }}
    </div>
    <div class="d-flex justify-content-around">
        <button class="btn btn-outline-primary col-3 align-self-center" type="submit">Enregistrer</button>
        <a class="btn btn-outline-primary col-4 align-self-center" href="{{ path('app_forgot_password_request') }}">Modifier le mot de passe</a>
        <a class="btn col-3 btn-danger align-self-center" href="{{ path('app_user_delete') }}">Supprimer</a>
    </div>
    {{ form_end(form) }}
</div>

templates/components/profilUser.html.twig
<div>
    <div class="card-body card-profil-body d-flex flex-column">
        <h4>Nombre d'article posté :</h4>
        <p class="align-self-center fw-bold fs-4">{{ stats.publication }}</p>
        <h4>Nombre de commentaire posté :</h4>
        <p class="align-self-center fw-bold fs-4">{{ stats.comment }}</p>
        <h4>Note du deal posté le plus hot : </h4>
        <p class="align-self-center fw-bold fs-4">{{ stats.mostHot }}</p>
        <h4>Moyenne des notes des deals postés sur 1an :</h4>
        <p class="align-self-center fw-bold fs-4"> {{ stats.average }}</p>
        <h4>Pourcentage des deals postés devenus hot</h4>
        <p class="align-self-center fw-bold fs-4">{{ stats.pourcentage }} %</p>
    </div>
</div>
<div class="tile">
    <div class="badge">
        <img class="badgeImg" src="{{ asset('build/images/badgeVote.png') }}" alt="Badge de Vote">
        <div class="badgeDetail">
            <h4>Surveillant :</h4>
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: {{ stats.vote*10 }}%;" aria-valuenow="{{ stats.vote }}" aria-valuemin="0" aria-valuemax="10"></div>
            </div>
            <div class="text">
                <p>Nombre d'article voté : {{ stats.vote }}</p>
            </div>
        </div>
    </div>
    <hr>
    <div class="badge">
        <img class="badgeImg" src="{{ asset('build/images/badgeCreation.png') }}" alt="Badge de Creation">
        <div class="badgeDetail">
            <h4>Cobaye :</h4>
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: {{ stats.publication*10 }}%;" aria-valuenow="{{ stats.publication }}" aria-valuemin="0" aria-valuemax="10"></div>
            </div>
            <div class="text">
                <p>Nombre d'article posté : {{ stats.publication }}</p>
            </div>
        </div>
    </div>
    <hr>
    <div class="badge">
        <img class="badgeImg" src="{{ asset('build/images/badgeComment.png') }}" alt="Badge de Commentaire">
        <div class="badgeDetail">
            <h4>Rapport de stage :</h4>
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: {{ stats.comment*10 }}%;" aria-valuenow="{{ stats.comment }}" aria-valuemin="0" aria-valuemax="10"></div>
            </div>
            <div class="text">
                <p>Nombre d'article commenté : {{ stats.comment }}</p>
            </div>
        </div>
    </div>
</div>

templates/components/publication.html.twig
<div class="card publication">
    <div class="d-flex h-100 w-100">
        <img class="card-img align-self-center p-4" src="{{ asset('uploads/publications/'~publication.image) }}"
             alt="Publication image">
        <div class="w-100 d-flex flex-column">
            <div class="card-body">
                {{ component('notation', { publication: publication }) }}
                <h5 class="card-title fw-bold">{{ publication.title }}</h5>
                <h6 class="fw-bold">
                    {% if publication.codePromo is not null %}
                        {% if publication.codePromo.typeDeReduction.label == 'Livraison gratuite' %}
                            {{ publication.codePromo.typeDeReduction.label }}
                        {% elseif publication.codePromo.typeDeReduction.label == 'Pourcentage' %}
                            Réduction de {{ publication.codePromo.value }}%
                        {% else %}
                            Réduction de {{ publication.codePromo.value }}€
                        {% endif %}
                    {% else %}
                        {{ publication.deal.price }}€ au lieu de
                       <span class="text-decoration-line-through">{{ publication.deal.regularPrice }}€</span>
                    {% endif %}
                </h6>
                <p class="card-text">{{ publication.description }}</p>
            </div>
            <div class="card-footer d-flex justify-content-between">
                <div class="card-text flex-column d-flex">
                    <small class="text-muted">
                        Publié le {{ publication.publishedAt|date('d/m/Y') }} par {{ publication.author.pseudo }}
                    </small>
                    {% if publication.codePromo is not null %}
                        <small class="text-muted">
                            Expire le {{ publication.codePromo.expiredAt|date('d/m/Y') }}
                        </small>
                    {% endif %}
                </div>
                <div>
                    {% if publication.codePromo is not null %}
                        <a href="{{ path('app_code_promo_show', {id: publication.codePromo.id}) }}" class="btn btn-primary text-white">Voir le code promo</a>
                    {% elseif publication.deal is not null %}
                        <a href="{{ path('app_deal_show', {id: publication.deal.id}) }}" class="btn btn-primary text-white">Voir le deal</a>
                    {% endif %}
                </div>
            </div>
        </div>


    </div>
</div>